version: '3.7'

services:
  nextcloud-loadbalance:
    image: nginx:1.13.1
    container_name: nextcloud-loadbalace
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    volumes:
      - ./nginx:/etc/nginx/conf.d
    environment:
      VIRTUAL_HOST: nc.milkiland.org
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: nc.milkiland.org
      LETSENCRYPT_EMAIL: admin@milkiland.com
    networks:
      proxy:

  nextcloud_db:
    image: mariadb:10.4.11
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    container_name: nextcloud_db
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    volumes:
      - ./nextclouddb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      proxy:

  nextcloud:
    image: nextcloud:18.0.0
    container_name: nextcloud
    restart: always
    deploy:
      mode: replicated
      replicas: 1
#      placement:
#        constraints:
#          - node.role == manager
    ports:
      - "8888:80"
    depends_on:
      - nextcloud_db
    links:
      - nextcloud_db
    volumes:
      - type: volume
        source: nextcloud
        target: /var/www/html
        volume:
          nocopy: true
    networks:
      proxy:

  nextcloud_redis:
    image: redis:5.0.7
    container_name: nextcloud_redis
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    volumes:
      - ./nextcloud_redis:/data
    networks:
      proxy:

volumes:
  nextcloud:
    driver_opts:
      type: "nfs4"
      o: "addr=10.21.10.13,nolock,soft,rw"
      device: ":/docker/nextcloud"

networks:
  proxy:
    external:
      name: nginx-proxy
